### ISSUE TITLE
Does not detect based on "Reset Password" privilege

### ISSUE THREAD

**Issue by HadManySons** [CyberArkLabs/ACLight#5]
Per example 2 on here: https://www.cyberark.com/threat-research-blog/shadow-admins-stealthy-accounts-fear/

The script should be able to detect when an account has the "Reset Password" permission for a domain admin account, but it does not. Small domain (1 DC, 8 computers, 5 users)

**Comment by Hechtov** [comment]
Thanks @HadManySons for reporting this issue.
Sorry for the delay. In our multiple tests, ACLight successfully discovered the scenario of a user that has reset password permission on a target domain admin account.
Can you share with us access to your environment or send us the scan results? We will need more details to check it out.

**Comment by HadManySons** [comment]
No, unfortunately, it was a virtual environment that has since been destroyed. It was a 2012 functional domain, Server 2012 R2. I don't have any more details than that. Sorry.

**Comment by Hechtov** [comment]
Ok, so I will do more ACLight scans in different environments to valid it discovers the ResetPassword permission.
We'll keep this issue opened for an additional few months, and see if more people encounter with this issue. Thanks.

**Comment by Hechtov** [comment]
Hi,
Since January we did 20+ different scans and it successfully detected users that had "reset password" permission on other privileged accounts (therefore, they were highlighted as Shadow Admins).
I will close this issue for now, if you encountered with this issue again, please contact me and we will investigate it more.
Thanks.
