### ISSUE TITLE
Server 2008 PowerShell v5.1 does not work

### ISSUE THREAD

**Issue by NickYan7** [CyberArkLabs/ACLight#9]
## Summary

For your information:
1. The winver is Windows Server 2008 R2 SP1, Ver6.1 (7601). And I've updated the .Net so the PowerShell version now is 5.1.
2. The **Server 08 is not in the Domain** .

![image](https://user-images.githubusercontent.com/27906343/149886333-b8f22823-519f-4c7a-9b91-d82dbc686a93.png)

What I want to do is **to execute the script on a machine that is not in the target domain** . So I played a tricky way:
1. Configuring the dns of the server 08 to point to the target DC.

2. Using cmd and execute:
c:\> runas /netonly /user:xxx.com\username powershell

3. now I have a domain user powershell, then:
PS c:\> import-module aclight2.psm1
PS c:\> Start-ACLsAnalysis

Unfortunately, I got some error...

![{177dd1fc-fc53-4b49-a71b-b70e8b8d51f3}](https://user-images.githubusercontent.com/27906343/149886187-1b46c4e5-c1a4-407d-af0b-26839117615f.png)

And the script was tested successfully on a Windows 10 which is in the domain.

Please check this, Thanks a lot.

**Comment by NickYan7** [comment]
Tested fail on a Windows 10 that is not in the domain, clearly it must be executed on the machine that domain joined.

**Comment by NickYan7** [comment]
Tested failed on a Server 08 that is domain joined.... the error reported 'the server is not operational'

![image](https://user-images.githubusercontent.com/27906343/149931300-fc05a210-5176-4897-80e4-217315d47180.png)

**Comment by Hechtov** [comment]
Hi @NickYan7 
I'm super happy you and other use the ACLight tool :)
The number of stars in this repository keeps rising, and it's great to see the value and help that the tool can provide people.

Regarding your issue, sorry it took time, I wrote the tool a while a go and progressed to other role since then.
It sounds like a specific issue with Server 2008, like you said it worked from Windows 10.
Because Server 2008 is quite old, my recommendation would be to run the scan from a more updated server version, maybe server 2012 or server 2016.
I'm closing this issue for now, but if it still doesn't work, please update me and I will try to replicate the issue and fix it.
